### ISSUE TITLE
ImportError: No module named django.core.management

### ISSUE THREAD

**Issue by percy3d** [diegotoral/generator-django#59]
hello,

I followed your instructions creating a virtualenv and then creating a new directory and cd'ing into that directory and running yo django and it installed everything or so it seems. 

I specified no repo and said I wanted django v1.7 to be installed. But when I try to run python manage.py runserver 127.0.0.1:9000 I get ImportError: No module named django.core.management. . Not sure what's missing here...no errors are indicated during the running of yo django.

**Comment by percy3d** [comment]
So, this doesn't in fact install django for you? And when you're asking which version to use, it's not to tell you which version we want you to install?....

**Comment by diegotoral** [comment]
You need to install the packages, with pip, after running the generator.

**Comment by jackygrahamez** [comment]
When I try to install the packes

```$ pip install  django.core.management
Collecting django.core.management
  Could not find any downloads that satisfy the requirement django.core.management
  No distributions at all found for django.core.management```

**Comment by diegotoral** [comment]
@jackygrahamez `django.core.management` isn't a Python package! Try `pip install django` or install from the project requirements with `pip install -r requirements/DEVELOPMENT`.
