### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by muminoff** [diegotoral/generator-django#60]
Why did you use 2 spaces for indentation?

**Comment by diegotoral** [comment]
Are you asking about JavaScript code?

JavaScript code tends to have a lot of nested code so with 2 spaces indentation I think the code looks great and fit better on any screen size.

For Python files we use 4 spaces, as suggested in [PEP8](https://www.python.org/dev/peps/pep-0008/#indentation).

**Comment by muminoff** [comment]
Nope. I am asking about Python code.

When I generate new Django app, I see 2 space indentations in py files. It is uncomfortable somehow. I am generating Django app as shown in Readme:

```shell
$ yo django:startapp
```

**Comment by diegotoral** [comment]
I'll check that! Thanks for the report!

**Comment by diegotoral** [comment]
Hey @muminoff, you were right!

I just fixed the problem. Try the new release!

Thanks again and good luck! :smile:

**Comment by muminoff** [comment]
:+1:
